---
title: "STAT 659 HW 6"
author: "Jack Cunningham"
format: pdf
editor: visual
---

1\)

```{r}
LI<-c(8,8,10,10,12,12,12,14,14,14,16,16,16,18,20,20,20,22,22,24,26,28,32,34,38,38,38)
y<-c(0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,0,1,1,1,0)
fit<-glm(y~LI,family=binomial(link=logit))
summary(fit)
```

```{r}
predict.glm(fit, data.frame(LI = 26), type = "response")
```

2\)

```{r}
exp(coef(fit)[2])
```

3\)

```{r}
LI_seq = seq(8,38,.1)
pred_seq <- predict.glm(fit,data.frame(LI = LI_seq),type = "response")
plot(LI_seq, pred_seq, ylim = c(0,1))
```

4\)

```{r}
beta = coef(fit)[2]
pi   = predict.glm(fit, data.frame(LI = 8), type = "response")
beta*pi*(1 - pi)
```

5\)

```{r}
pi = predict.glm(fit,type = "response")
mean(beta*pi*(1 - pi))
```

7\)

```{r}
library(lmtest)
lrtest(fit)
```

```{r}
test_stat = 34.372 - 26.073
```

```{r}
exp(confint.default(fit))
```

```{r}
exp(confint(fit))
```

10\)

```{r}
shuttle <- read.table("Shuttle.txt",header = TRUE)
head(shuttle)
```

```{r}
fit <- glm(TD ~ Temp, family = binomial, data = shuttle)
summary(fit)
```

12\)

```{r}
predict.glm(fit, data.frame(Temp = 31), type = "response")
```

13\)

```{r}
beta_0 = coef(fit)[1]
beta_1 = coef(fit)[2]
-beta_0/beta_1
predict.glm(fit, data.frame(Temp = -beta_0/beta_1), type = "response")
```

14\)

```{r}
.5*(1 - .5)*beta_1
```

16\)

```{r}
kyphosis <- read.table("Kyphosis.txt",header = TRUE)
head(kyphosis)
```

```{r}
plot(kyphosis$x, kyphosis$y)
```

17\)

```{r}
fit <- glm(y ~ x + I(x^2),data = kyphosis, family = binomial)
summary(fit)
```

18\)

```{r}
age_seq = seq(0, 250, .5)
prob_seq = predict.glm(fit, data.frame(x = age_seq), type = "response")
plot(age_seq, prob_seq)
```

19\)

```{r}
fit_reduced <- glm(y ~ x, family = binomial, data = kyphosis)
lrtest(fit,fit_reduced)
```

22\)

```{r}
crab <- read.table("crabs.txt", header = TRUE)
head(crab)
```

```{r}
fit <- glm(y ~ factor(color)*width,data = crab, family = binomial)
summary(fit)
```

23\)

```{r}
width_seq = seq(20, 34, .5)
color_2 = rep(2,29)
color_3 = rep(3,29)
color_4 = rep(4,29)
color_5 = rep(5,29)

probs_2 = predict.glm(fit, data.frame(width = width_seq, color = color_2), 
            type = "response")
probs_3 = predict.glm(fit, data.frame(width = width_seq, color = color_3), 
            type = "response")

probs_4 = predict.glm(fit, data.frame(width = width_seq, color = color_4), 
            type = "response")

probs_5 = predict.glm(fit, data.frame(width = width_seq, color = color_5), 
            type = "response")
plot(width_seq, probs_2,type = "l",ylim = c(0,1), col = "red")
lines(width_seq, probs_3, type = "l", col = "green")
lines(width_seq, probs_4, type = "l", col = "blue")
lines(width_seq, probs_5, type = "l", col = "yellow")
```

24\)

```{r}
fit_reduced = glm(y ~ factor(color) + width,data = crab, family = binomial)
lrtest(fit, fit_reduced)
```
