---
title: "STAT 659 HW 3"
format: pdf
editor: visual
---

1/2)

```{r}
data = matrix(c(21,53,94,159, 372, 249, 110, 221, 83), nrow = 3, ncol = 3)
exp  = matrix(c(35.8 ,79.7, 52.5, 166.1, 370, 244, 88.1, 196.4, 129.5),
              nrow = 3, ncol = 3)
chisq.test(data, p = exp/sum(exp))
X2 <- sum((data - exp)^2/exp)
1 - pchisq(X2, 4)
```

6\)

```{r}
mosaicplot(data)
```

7\)

```{r}
lineartrend<-function(data,rownums,colnums){
  numericdata<-matrix(NA,nrow=0,ncol=2)
  for(i in 1:nrow(data)){
    for(j in 1:ncol(data)){
      ni<-data[i,j]
      adddata<-cbind(rep(rownums[i],ni),rep(colnums[j],ni))
      numericdata<-rbind(numericdata,adddata)
    }
  }
  fit<-cor.test(numericdata[,1],numericdata[,2])
  r<-fit$estimate
  m2<-fit$estimate^2*(nrow(numericdata)-1)
  pvalue<-1-pchisq(m2,1)
  ans<-cbind(r,round(m2,4),pvalue)
  colnames(ans)<-c("r","M2","p-value")
  ans
}


data<-rbind(c(21,159,110),c(53,372,221),c(94,249,83))
lineartrend(data,c(1,2,3),c(1,2,3))
```

8\)

```{r}
obs_data = matrix(data = c(871,347,821,42,336,83), nrow = 2, ncol = 3,
              dimnames = list(c("White","Black"),
                              c("Democrat","Republican","Independent")))
obs_data
```

```{r}
n = sum(obs_data)
row_totals <- matrix(rep(apply(obs_data,1,sum),3),ncol = 3)
col_totals <- matrix(rep(apply(obs_data,2,sum), each = 2),nrow = 2)
exp_totals <- (row_totals*col_totals)/n
exp_totals
```

```{r}
X2 = sum((obs_data - exp_totals)^2/exp_totals)
X2
```

9\)

```{r}
1 - pchisq(X2, df = 2)
```

```{r}
chisq.test(obs_data, exp_totals/totals)
```

```{r}
std_res = (obs_data - exp_totals)/
  sqrt(exp_totals*(1 - row_totals/n)*(1 - col_totals/n))
std_res
```

12\)

14\)

```{r}
X2 = 69.2
p_value = 1 - pchisq(X2, df = 4)
p_value
```

16\)

```{r}
obs_data = matrix(data = c(178,570,138,138,648,252,108,442,252), nrow = 3,
                  dimnames = list(c("LHS","HS","DG"),c("FUND","MOD","LIB")))
obs_data
mosaicplot(t(obs_data))
```

17\)

```{r}
lineartrend(obs_data,c(1,2,3),c(1,2,3))
```

19\)

```{r}
obs_data = matrix(data = c(2,4,13,3,2,6,22,4,0,1,15,8,0,3,13,8),byrow = TRUE,
                  nrow = 4, dimnames = list(c("<5","5-15","15-25",">25"),
                                            c("very diss","little","mod",
                                              "very sat")))
obs_data
```

```{r}
n = sum(obs_data)
row_totals <- matrix(rep(apply(obs_data,1,sum),4),ncol = 4)
col_totals <- matrix(rep(apply(obs_data,2,sum), each = 4),nrow = 4)
exp_totals <- (row_totals*col_totals)/n
exp_totals
```

```{r}
X2 = sum((obs_data - exp_totals)^2/exp_totals)
X2
```

20\)

```{r}
1 - pchisq(X2, df = 9)
```

23\)

```{r}
lineartrend(obs_data,c(3,10,20,35),c(1,3,4,5))
```

27\)

```{r}
obs_data = matrix(c(7,0,8,15),nrow = 2,dimnames = list(c("Treatment","Control"),
                                                      c("Achieve","Not Achieve")))
obs_data
```

```{r}
fisher.test(obs_data,alternative = "greater")
```

29\)

```{r}
data = matrix(c(21,15,2,3),nrow = 2, dimnames = list(c("Surgery", "Rad"),
                                                     c("Control","N Control")))
data
```

```{r}
fisher.test(data)
```

```{r}
library(epitools)
ormidp.test(21,2,15,3)
```

31\)

```{r}
data = c(15,18,8,22,10,19,14,14,18,12)
exp_data = rep(15,10)
X2 = sum((data - exp_data)^2/exp_data)
X2
```

32\)

```{r}
1 - pchisq(X2,9)
```

34\)

```{r}
n = 1301
data = c(773,221,238,69)
exp_props = c(9/16,3/16,3/16,1/16)
exp_data  = n*exp_props
X2 = sum((data - exp_data)^2/exp_data)
X2
```

35\)

```{r}
1 - pchisq(X2, 3)
```

37\)

```{r}
data = c(1997, 906, 904, 32)
n = sum(data)
```

```{r}
theta = seq(0,1,.00001)
log_like = 1997*log(1/4*(2+theta)) + 906*log(1/4*(1-theta)) +
  904*log(1/4*(1-theta))+32*log(1/4*theta)
theta_hat = theta[which.max(log_like)]
```

```{r}
plot(x = theta, y = log_like, type = "l")
```

```{r}
exp_data = n*1/4*c(2+theta_hat, 1 - theta_hat, 1 - theta_hat, theta_hat)
exp_data
```

38\)

```{r}
X2 = sum((data - exp_data)^2/exp_data)
X2
```

39\)

```{r}
1 - pchisq(X2, 3)
```
