---
title: "JC STAT 659 HW 4"
author: "Jack Cunningham"
format: pdf
editor: visual
---

```{r}
library(epitools)
library(DescTools)
```

2\)

```{r}
smith_2005 <- 104/411
jones_2005 <- 12/48
smith_2006 <- 45/140
jones_2006 <- 183/583
smith_combined <- 149/551
jones_combined <- 195/630

```

3\)

```{r}
odds_ratio_given_white <- (19*52)/(132*11)
odds_ratio_given_white
```

4\)

```{r}
odds_ratio_given_black <- (0*97)/(9*6)
```

5\)

```{r}
odds_ratio_marginal <- (19*149)/(141*17)
```

7\)

8\)

```{r}
data <- array(c(512,89,313,19,
                353,17,207,8,
                120,202,205,391,
                138,131,279,244,
                53,94,138,299,
                22,24,351,317),dim = c(2,2,6))
data2 <- c(512,89,313,19,
                353,17,207,8,
                120,202,205,391,
                138,131,279,244,
                53,94,138,299,
                22,24,351,317)
```

```{r}
oddsratio(data[,,1], method = "wald")$measure
```

```{r}
oddsratio(data[,,2], method = "wald")$measure
```

```{r}
oddsratio(data[,,3], method = "wald")$measure
```

```{r}
oddsratio(data[,,4], method = "wald")$measure
```

```{r}
oddsratio(data[,,5], method = "wald")$measure
```

```{r}
oddsratio(data[,,6], method = "wald")$measure
```

10\)

```{r}
BreslowDayTest(data)
```

13\)

```{r}
mantelhaen.test(data, correct = FALSE)
```

17\)

```{r}
data_dep_2_6 = data[,,2:6]
BreslowDayTest(data_dep_2_6)
```

20\)

```{r}
data <- array(c(24,47,9,12,10,45,3,8,5,57,4,9,16,54,7,10,7,59,4,12),dim = c(2,2,5))
data
```

```{r}
oddsratio(data[,,1], method = "wald")$measure
```

```{r}
oddsratio(data[,,2], method = "wald")$measure
```

```{r}
oddsratio(data[,,3], method = "wald")$measure
```

```{r}
oddsratio(data[,,4], method = "wald")$measure
```

```{r}
oddsratio(data[,,5], method = "wald")$measure
```

```{r}
marginal_data <- apply(data,MARGIN = c(1,2), sum)
marginal_data
```

21\)

```{r}
marginal_data[1,1]*marginal_data[2,2]/(marginal_data[2,1]*marginal_data[1,2])
```

24\)

```{r}
BreslowDayTest(data)
```

27\)

```{r}
mantelhaen.test(data, correct = FALSE)
```

34\)

```{r}
.6930 - .0662*12
```

37\)

```{r}
result = c(rep(1,48),rep(0,17114),rep(1,38),rep(0,14502),
           rep(1,5),rep(0,793),rep(1,1),rep(0,127),rep(1,1),rep(0,38))
alc    = c(rep(0,48 + 17114),rep(.5,38 + 14502), rep(1.5, 5 + 793),
           rep(4, 1 + 127), rep(7, 1 + 38))
summary(glm(result ~ alc, family = binomial(link = "identity")))
```

38\)

```{r}
p_0 = 0.0025417
```

39\)

```{r}
p_7 = p_0 + 0.0010787*7
```

40\)

```{r}
rr_7_0 = p_7/p_0
rr_7_0
```

41\)

```{r}
result = c(rep(1,48),rep(0,17114),rep(1,38),rep(0,14502),
           rep(1,5),rep(0,793),rep(1,1),rep(0,127),rep(1,1),rep(0,38))
alc    = c(rep(0,48 + 17114),rep(1,38 + 14502), rep(2, 5 + 793),
           rep(3, 1 + 127), rep(4, 1 + 38))
summary(glm(result ~ alc, family = binomial(link = "identity")))
```

```{r}
pr_0 <- 0.0025911
pr_7 <- 0.0025911 + 0.0005011*7
```

```{r}
rr_7_0 = pr_7/pr_0
rr_7_0
```

43\)

```{r}
result = c(rep(1,48),rep(0,17114),rep(1,38),rep(0,14502),
           rep(1,5),rep(0,793),rep(1,1),rep(0,127),rep(1,1),rep(0,38))
alc    = c(rep(0,48 + 17114),rep(.5,38 + 14502), rep(1.5, 5 + 793),
           rep(4, 1 + 127), rep(7, 1 + 38))
fit <- glm(result ~ alc, family = binomial())
summary(fit)
```

```{r}
p_0 = predict(fit, newdata = data.frame(alc = 0), type = "response")
p_0
p_7 = predict(fit, newdata = data.frame(alc = 7), type = "response")
p_7
rr_7_0 = p_7/p_0
rr_7_0
```

```{r}
result = c(rep(1,48),rep(0,17114),rep(1,38),rep(0,14502),
           rep(1,5),rep(0,793),rep(1,1),rep(0,127))
alc    = c(rep(0,48 + 17114),rep(.5,38 + 14502), rep(1.5, 5 + 793),
           rep(4, 1 + 127))
fit <- glm(result ~ alc, family = binomial())
summary(fit)

```

```{r}
p_0 = predict(fit, newdata = data.frame(alc = 0), type = "response")
p_0
p_7 = predict(fit, newdata = data.frame(alc = 7), type = "response")
p_7
rr_7_0 = p_7/p_0
rr_7_0
```

45\)

46\)

```{r}
pi_hat = -.0003 + 0.0304*.0774
pi = 0.0079
pi/pi_hat
```

47\)

```{r}
horseshoe <- as.data.frame(read.delim("horseshoe.txt", sep = ""))
```

```{r}
fit <- glm(data = horseshoe, y ~ weight, family = binomial(link = "identity"))
```

```{r}
fit <- lm(data = horseshoe, y ~ weight)
summary(fit)
```

49\)

```{r}
predict(fit, newdata = data.frame(weight = 5.2), type = "response")
```

51\)

```{r}
fit <- glm(data = horseshoe, y ~ weight, family = binomial())
summary(fit)
```

```{r}
predict(fit, data.frame(weight = 5.2), type = "response")
```

54\)

```{r}
response = c(rep(1,24),rep(0,1355),rep(1,35),rep(0,603),rep(1,21),rep(0,192),
             rep(1,30),rep(0,224))
score_1 = c(rep(1,24 + 1355), rep(2,35 + 603), rep(3, 21 + 192), rep(4, 30 + 224))
score_2 = c(rep(0,24 + 1355), rep(1,35 + 603), rep(2, 21 + 192), rep(3, 30 + 224))
score_3 = c(rep(0,24 + 1355), rep(2,35 + 603), rep(4, 21 + 192), rep(6, 30 + 224))
score_4 = c(rep(0,24 + 1355), rep(2,35 + 603), rep(6, 21 + 192), rep(7, 30 + 224))
score_5 = c(rep(0,24 + 1355), rep(20,35 + 603), rep(60, 21 + 192), 
            rep(70, 30 + 224))

```

```{r}
model_1 = glm(response ~ score_1, family = binomial())
model_2 = glm(response ~ score_2, family = binomial())
model_3 = glm(response ~ score_3, family = binomial())
model_4 = glm(response ~ score_4, family = binomial())
model_5 = glm(response ~ score_5, family = binomial())
```

```{r}
coef(model_1)
coef(model_2)
coef(model_3)
coef(model_4)
coef(model_5)
```

```{r}
predict(model_1, newdata = data.frame(score_1 = unique(score_1)), 
        type = "response")
predict(model_2, newdata = data.frame(score_2 = unique(score_2)),
        type = "response")
predict(model_3, newdata = data.frame(score_3 = unique(score_3)),
        type = "response")
predict(model_4, newdata = data.frame(score_4 = unique(score_4)),
        type = "response")
predict(model_5, newdata = data.frame(score_5 = unique(score_5)),
        type = "response")
```

56\)

```{r}
library(tidyverse)
credit <- as.data.frame(read.delim("Credit.txt", sep = "")) |> 
  mutate(cardholders = cards, noncardholders = n - cardholders)
```

```{r}
y = c()
for(i in 1:dim(credit)[1]){
  holders = rep(1,credit[i,"cardholders"])
  non_holders = rep(0, credit[i,"noncardholders"])
  y = c(y,holders,non_holders)
}
income = c()
for(i in 1:dim(credit)[1]){
  income = c(income, rep(credit[i,"income"],credit[i,"n"]))
}
```

```{r}
fit = glm(formula = y ~ income, family = binomial())
summary(fit)
```

58\)

```{r}
predict(fit, newdata = data.frame(income = 33.4), type = "response")
```
