---
title: "STAT 659 HW 5"
author: "Jack Cunningham"
format: html
editor: visual
---

1/2/3)

```{r}
t_a = c(8,7,6,6,3,4,7,2,3,4)
t_b = c(9,9,8,14,8,13,11,5,7,6)
counts = c(t_a,t_b)
treatment = c(rep(0,10),rep(1,10))
fit <- glm(counts ~ treatment, family = poisson)
summary(fit)
```

4\)

```{r}
fit_reduced <- glm(counts ~ 1, family = poisson)
L_full = 27.857
L_red  = 16.268
L_diff = L_full - L_red
1 - pchisq(L_diff,df = 1)
```

```{r}
anova(fit_reduced, fit)
```

```{r}
library(lmtest)
lrtest(fit, fit_reduced)
```

6/7)

```{r}
exp(confint(fit))
```

8\)

```{r}
crabs <- read.table("crabs.txt",header = TRUE)
```

```{r}
fit <- glm(satell ~ weight, family = poisson, data = crabs)
summary(fit)
```

9\)

```{r}
predict.glm(fit, newdata = data.frame(weight = 2.44), type = "response")
```

10\)

```{r}
confint(fit)
```

13\)

```{r}
dev_full = 632.79
dev_red  = 560.87
dev_diff = dev_full - dev_red
```

```{r}
fit_red <- glm(satell ~ 1, family = poisson, data = crabs)
```

```{r}
lrtest(fit_red, fit)
```

15\)

```{r}
library(MASS)
fit_nb = glm.nb(satell ~ weight, data = crabs)
summary(fit_nb)
```

17\)

```{r}
AIC(fit)
AIC(fit_nb)
```

```{r}
library(pscl)
zero_weight_poisson <- zeroinfl(satell ~ weight|weight, data = crabs)
AIC(zero_weight_poisson)
zero_weight_nb <- zeroinfl(satell ~ weight|weight, data = crabs,
                                dist = "negbin")
AIC(zero_weight_nb)

zero_int_poisson <- zeroinfl(satell ~ weight|1, data = crabs)
AIC(zero_int_poisson)
zero_int_nb <- zeroinfl(satell ~ weight|1, data = crabs,
                                dist = "negbin")
AIC(zero_int_nb)
```

19\)

```{r}
Cancerdata <- read.table("lungCancer.txt",header = TRUE)
```

```{r}
fit <- glm( count ~ factor(histology) + factor(stage) + factor(time), family=poisson(link="log"),offset=log(risktime),data= Cancerdata)
summary(fit)
```

```{r}
fit_interaction <- fit <- glm(count ~ factor(histology) + factor(stage)*factor(time), family=poisson(link="log"),offset=log(risktime),data=Cancerdata)
summary(fit_interaction)
```

```{r}
library(car)
Anova(fit_interaction)
```

21\)

```{r}
fit_simple = glm( count ~ factor(stage) + factor(time), family=poisson(link="log"),offset=log(risktime),data= Cancerdata)
  
```

```{r}
lrtest(fit_interaction, fit_simple)
```

22\)

```{r}
summary(fit_simple)
```

26\)

```{r}
soccer <- read.table("soccerteams.txt",header = TRUE)
fit <- glm(arrests ~ 1, offset = log(attendance),
           data = soccer, family = poisson)
summary(fit)
```

27\)

```{r}
fit_teams <- glm(arrests ~ teams, offset = log(attendance),
           data = soccer, family = poisson)
summary(fit_teams)
```

```{r}
library(tidyverse)
soccer |> 
  mutate(rate = arrests/attendance) |> 
  arrange(desc(rate))
```

28\)

```{r}
fit_nb <- glm.nb(arrests ~ 1 + offset(log(attendance)),
           data = soccer)
summary(fit_nb)
```

```{r}
1/3.135 + c(-1,1)*1.96*.920
```

31\)

```{r}
smokers <- read.table("smokerdeaths.txt",header = TRUE)
```

```{r}
smokers_df <- smokers |> 
  mutate(non_rate = 1000*(nondeaths)/(nonyears), smoke_rate =
           1000*(smokedeaths)/(smokeyears)) |> 
  mutate(rel_risk = non_rate/smoke_rate)
smokers_df
```

34\)

```{r}
smokers_df_model <- data.frame(
  age = c('35-44','35-44','45-54','45-54','55-64','55-64',
          '65-74','65-74','75-84','75-84'),
  smoker = c(0,1,0,1,0,1,0,1,0,1),
  years  = c(18793,52407,10673,43248,5710,28612,2585,12663,1462,5317),
  deaths = c(2,32,12,104,28,206,28,186,31,102)
)
  
```

```{r}
fit <- glm(deaths ~ age + smoker + offset(log(years)), 
           family = poisson(), data = smokers_df_model)
summary(fit)
```

37\)

```{r}
smokers_df_model_2 <- data.frame(
  age_num = c(1,1,2,2,3,3,4,4,5,5),
  age_cat = c('35-44','35-44','45-54','45-54','55-64','55-64',
          '65-74','65-74','75-84','75-84'),
  smoker = c(0,1,0,1,0,1,0,1,0,1),
  years  = c(18793,52407,10673,43248,5710,28612,2585,12663,1462,5317),
  deaths = c(2,32,12,104,28,206,28,186,31,102)
)
```

```{r}
fit_2 <- glm(deaths ~  age_cat + smoker + age_num:smoker + offset(log(years)), 
           family = poisson(), data = smokers_df_model_2)
summary(fit_2)
```

```{r}
lrtest(fit_2,fit)
```
