---
title: "STAT 659 HW 9"
author: "Jack Cunningham"
format: pdf
editor: visual
---

1\)

```{r}
log(.5/(1 - .5))
```

2\)

```{r}
p1 <- NULL
for(i in 1:10000){
  n <- 170
  x <- runif(n, 0, 10)
  model <- 2 - .2*x
  prob <- exp(model)/(1 + exp(model))
  y <- rbinom(n, 1, prob)
  fit <- glm(y ~ x, family = binomial)
  p1 <- c(p1,summary(fit)$coefficients[2,4])
}
mean(p1 < .05)
```

3/4)

```{r}
avg_dog_logit <- log(.5/(1 - .5))
one_sd_dog_logit <- log(.8/(1 - .8))
beta_1 <- (one_sd_dog_logit - avg_dog_logit)/2
beta_0 <- avg_dog_logit - beta_1*10
```

5\)

```{r}
p1 <- NULL
for(i in 1:10000){
  n <- 37
  x <- rnorm(n, 10, 2)
  model <- beta_0 + beta_1*x
  prob <- exp(model)/(1 + exp(model))
  y <- rbinom(n, 1, prob)
  fit <- glm(y ~ x, family = binomial)
  p1 <- c(p1,summary(fit)$coefficients[2,4])
}
mean(p1 < .05)
```

6\)

```{r}
niter <- 1000
p <- matrix(NA, nrow = niter, ncol = 4)
for(i in 1:niter){
  for(j in 1:4){
      n <- 120
      x <- runif(n, 0, 100)
      model <- -5 + .1*x
      prob <- exp(model)/(1 + exp(model))
      y <- rbinom(n, 1, prob)
      fit <- glm(y ~ x, family = binomial)
      p[i,j] <- summary(fit)$coefficients[2,4]
    }
}
mean(p[,1] < .05 & p[,2] < .05 & p[,3] < .05 & p[,4] < .05)
```

7\)

```{r}
data <- read.table("fugitives.txt",header = TRUE)
head(data)
```

```{r}
library(MASS)
fit <- lda(tactic ~ finances + intelligence + violence + age, data = data)
fit
```

```{r}
plot(fit,dimen = 2, col = as.numeric(factor(data$tactic)))
```

9\)

```{r}
table(data$tactic, predict(fit, type = "response")$class)
```

10\)

```{r}
data <- read.table("doctor.txt", header = TRUE)
head(data)
```

```{r}
fit <- lda(Diagnosis ~ fever + sweat + bp + tongue + energy + pain, data = data)
fit
```

11\)

```{r}
table(data$Diagnosis, predict(fit, type = "response")$class)
```

13\)

```{r, fig.height=8, fig.width=12}
plot(fit, dimen = 1)
```

14\)

```{r}
data <- read.table("ceos.txt", header = TRUE)
head(data)
```

```{r}
sdata <- scale(data)
set.seed(659)
library(factoextra)
fviz_nbclust(sdata, kmeans, method = "wss")
```

```{r}
set.seed(659)
fit <- kmeans(sdata, 3, nstart = 25)
fit$centers
fviz_cluster(fit, sdata)
```

18\)

```{r}
data <- read.table("faces.txt",header = TRUE)
head(data)
```

```{r}
set.seed(659)
sdata <- scale(data)
fit <- kmeans(sdata, 4, nstart = 25)
fit$centers
fviz_cluster(fit, sdata)
```

19\)

```{r}
data <- read.table("buywidget.txt", header = TRUE)
data$buy <- factor(data$buy)
```

```{r, fig.width = 12, fig.height = 12}
library(tidymodels)
fit <- fit(decision_tree(mode = "classification"), buy ~ income + education + age, data = data)
library(rpart.plot)
rpart.plot(fit$fit, type = 2)
```

```{r}
table(data$buy, predict(fit,new_data = data)$.pred_class)
```

21\)

```{r}
set.seed(659)
library(xgboost)
cov <- as.matrix(data[,-1])
y <- as.numeric(as.factor(data[,1])) -1
fit <- xgboost(data = cov, label = y, nround = 4, objective = "binary:logistic")
```

```{r}
library(DiagrammeR)
xgb.plot.importance(xgb.importance(names(y), model = fit))
```

```{r}
table(data[,1],ifelse(predict(fit, newdata = cov) > .5, "not","buy"))
```

24\)

```{r}
data <- read.table("emails.txt",header = TRUE)
head(data)
```

```{r}
cov <- data[,-1]
cov$links <- ifelse(cov$flags == "links",1,0)
cov$foreign <- ifelse(cov$flags == "foreign", 1, 0)
cov$urgency <- ifelse(cov$flags == "urgency",1, 0)
cov$isolation <- ifelse(cov$flags == "isolation", 1, 0)
cov <- as.matrix(cov[,-4])
y <- as.numeric(as.factor(data[, 1])) - 1
```

```{r}
set.seed(659)
fit <- xgboost(data = cov, label = y, objective = "multi:softmax",
               num_class = 4, nround = 3)
```

```{r}
xgb.plot.importance(xgb.importance(names(y), model = fit))
```

```{r}
table(data[,1],predict(fit, newdata = cov))
```

```{r}
predict(fit, newdata = as.matrix(data.frame(hour = 0, length = 13,
                                               mispelings = 2, links = 0,
                                               foreign = 0, urgency = 1,
                                               isolation = 0)))
```

```{r}
predict(fit, newdata = as.matrix(data.frame(hour = 8, length = 13,
                                               mispelings = 2, links = 0,
                                               foreign = 0, urgency = 1,
                                               isolation = 0)))
```
