# Method	Code
# test p wald	by hand (phat-p)/sqrt(phat*(1-phat)/n)
# test p Score	prop.test(x,n,alternative="two.sided",correct=FALSE)
# test p fishers	binom.test(x,n,alternative="two.sided",correct=FALSE)
# CI p Wald	binom::binom.confint(x,n,method="asymptotic")
# CI p Score	binom::binom.confint(x,n,method="wilson")
# CI p AC	binom::binom.confint(x,n,method="agresti-coull")
# CI p Fishers	binom::binom.confint(x,n,method="exact")
# CI p Jeffrey	binom::binom.confint(x,n,method="bayes")
# Midp CI	exactci::binom.exact(x,n,p, alternative = "less", midp = TRUE)
# CI poisson Wald	by hand ybar +- Z sqrt(Ybar/n)
# CI poisson Score	by hand  ybar+Z^2/2n+Z/sqrt(n) sqrt(ybar+Z^2/4n)
# CI poisson GOF	by hand Z={(s^2/xbar)-1}sqrt((n-1)/2)
# Relative Risk	by hand p1/p2
# RR CI	eiptools::riskratio.wald(datamatrix)
# Odds Ratio wald CI	epitools::oddsratio(data,method="wald")$measure
# Test p1-p2 exact	epitools::oddsratio(data,method="fisher")$p.value
# Odds Ratio Mid p	epitools::oddsratio(data)
# Test odds ratio=1	epitools::oddsratio(data)
# CI Odds Ratio	epitools::oddsratio(data)
# CI p1-p2 Wald	DescTools::BinomDiffCI(x1,n1,x2,n2,method="wald")
# CI p1-p2 Score	DescTools::BinomDiffCI(x1,n1,x2,n2,method="score")
# CI p1-p2 Newcomb	By hand
# CI p1-p2 AgrestiCaffo	DescTools::BinomDiffCI(x1,n1,x2,n2,method="ac")
# Breslow Day	DescTools::BreslowDayTest(data)
# Mantel Heanszel	mantelhaen.test(data,correct=FALSE)
# X2 GOF	chisq.test(data,p=prop)
# X2 Test indpendence	chisq.test(data)
# Logistic 0/1	glm(y~x,family=binomial)
# Logistic columns	glm(cbind(y1,y2)~x,family=binomial)
# Logistic counts	glm(y/n~x,weights=n,family=binomial)
# Logistic Linear	fit<-glm(y~x,family=binomial(link="identity"))
# Plot effects	plot(yhat~xhat,type="l")
# Logistic prediction	predict(fit,newdata=data.frame(x=10),type="response")
# Logistic predictions	predict(fit,newdata=data,type="response")
# Logistic confusion table	table(data$y,preds)
# LR test nested	anova(fit1,fit2)
# LR test nested pvalue	lmtest::lrtest(fit1,fit2)
# LT test	by hand Chisquare(residual1-residual2,df1-df2)
# CI for beta Wald	confint.default(fit)
# CI for beta L Profile	confint(fit)
# Probit 0/1	glm(y~x,family=binomial(link="probit"))