---
title: "JC STAT 659 Practice Final A"
author: "Jack Cunningham"
format: pdf
editor: visual
---

1\)

```{r}
x <- 6
n <- 22

prop.test(x,n,alternative="two.sided",correct=FALSE)

binom.test(x,n,alternative="two.sided")
```

3\)

(p-pi)/sqrt(pi(1-pi)/n)

```{r}
2.3*(sqrt(.2*(1 - .2)/100)) + .2
```

4\)

```{r}
library(DescTools)
data <- array(c(100,300,200,90,70,180,150,60,30,90,60,12), dim = c(2,2,3))
#mantelhaen.test(data,correct=FALSE)
```

```{r}
DescTools::BreslowDayTest(data)
```

5\)

```{r,warning=FALSE}
p1 <- NULL
 for(i in 1:5000){
   n <- 15
   x <- runif(n, 50, 120)
   model <- -10 + .1*x
   prob <- exp(model)/(1 + exp(model))
   y <- rbinom(n, 1, prob)
   fit <- glm(y ~ x, family = binomial)
   p1 <- c(p1,summary(fit)$coefficients[2,4])
 }
mean(p1 < .05)
```

6\)

```{r,warning=FALSE}
p1 <- NULL
 for(i in 1:5000){
   n <- 15
   x <- runif(n, 50, 120)
   model <- -2 + .01*x
   prob <- exp(model)/(1 + exp(model))
   y <- rbinom(n, 1, prob)
   fit <- glm(y ~ x, family = binomial)
   p1 <- c(p1,summary(fit)$coefficients[2,4])
 }
mean(p1 < .05)
```

7\)

```{r}
data <- read.table("talent.txt",header = TRUE)
data$accent <- as.factor(data$accent)
head(data)
```

```{r}
fit <- glm(star ~ age + timber + tone + volume + accent,data = data, 
           family = binomial())
summary(fit)
```

```{r}
fit2 <- glm(star ~ age*timber + tone + volume + accent,data = data, 
           family = binomial())
summary(fit2)
```

```{r}
library(lmtest)
lrtest(fit, fit2)
```

```{r}
fit_2_probit <-glm(star ~ age*timber + tone + volume + accent,data = data, 
           family = binomial(link = "probit"))
summary(fit_2_probit)
```

```{r}
BIC(fit2);BIC(fit_2_probit)
```

10\)

```{r}
data <- read.table("graduatestudents.txt", header = TRUE)
head(data)
```

```{r}
set.seed(659)
sdata <- scale(data)
fit <- kmeans(sdata,3,nstart=25)
fit
```

12\)

```{r}
factoextra::fviz_cluster(fit,sdata)
```

13\)

```{r}
data <- read.table("onlineattacks.txt",header = TRUE)
head(data)
```

```{r}
fit <- glm(attacks ~ accounts + users + hour + year, data = data,
           family = poisson())
summary(fit)
```

```{r}
predictions <- predict.glm(fit, newdata = data.frame(
  accounts = c(10,20,30,40,50,60), users = c(275, 300, 300, 320, 320, 350),
  hour = c(10,10,10,15,15,20), year = c(4,4,5,5,6,10)
), type = "response")
predictions
```

14\)

```{r}
data <- read.table("pregnancy.txt", header = TRUE)
head(data)
```

```{r}
data$pregnant <- ifelse(data$pregnant == "Yes",1,0)
data$religion <- ifelse(data$religion == "spiritual",1,0)
data$animals <- ifelse(data$animals == "like",1,0)
data$humor <- ifelse(data$humor == "high",1,0)

data$hobbynone <- ifelse(data$hobby == "none",1,0)
data$hobbymedia <- ifelse(data$hobby == "media",1,0)
data$hobbyoutdoor <- ifelse(data$hobby == "outdoor",1,0)
data$hobbyart <- ifelse(data$hobby == "art",1,0)


head(data)
```

```{r}
cov <- as.matrix(data[,c(-1, -5)])
y <- data[,1]
```

```{r}
library(xgboost)
set.seed(659)
fit <- xgboost::xgboost(data=cov ,label=y,nrounds=4,objective="binary:logistic")
```

15\)

```{r}
library(vip)
vip::vip(fit)
```

16\)

```{r}
table(y,ifelse(predict(fit,newdata=cov)>.5,1,0))
```

17\)

```{r}
data <- read.table("trafficdestinations.txt",header = TRUE)
head(data)
```

```{r}
cov <- as.matrix(data[,2:4])
y <- as.numeric(as.factor(data[, 1])) - 1
```

```{r}
set.seed(659)

fit <- xgboost::xgboost(data=cov,label=y,nround=2,objective="multi:softmax",num_class=5)
```

```{r}
vip::vip(fit)
```

```{r}
odds_lots_of_water <- 1098*778/(1493*557)
odds_scarce_water <- 412*119/(89*313)
conditional_odds <- (1098 + 412)*(778 + 119)/((1493 + 89)*(557 + 313))
odds_lots_of_water;odds_scarce_water;conditional_odds
```

19\)

```{r}
data <- read.table("villain.txt", header = TRUE)
head(data)
```

```{r}
library(pscl)
fit <- pscl::zeroinfl(villainized ~ scars + friends + minorkey|minorkey + friends,data=data)
summary(fit)
```

20\)

```{r,warning=FALSE}
niter <- 1000
p <- matrix(NA,nrow = niter, ncol = 3)
for(i in 1:niter){
   n <- 90
   for(j in 1:3){
     x <- runif(n, 0, 1)
     if(j == 1){model <-  1 - 2*x}
     if(j == 2){model <- -3 + 8*x}
     if(j == 3){model <- -4 + 4*x}
      prob <- exp(model)/(1 + exp(model))
      y <- rbinom(n, 1, prob)
      fit <- glm(y ~ x, family = binomial)
      p[i,j] <- summary(fit)$coefficients[2,4]
     }
 }
mean(p[,1] < .05|p[,2] < .05|p[,3] < .05)
```

```{r}
niter <- 5000
p <- matrix(NA,nrow = niter, ncol = 3)
for(i in 1:niter){
   n <- 170
   x1 <- runif(n, 0, 1)
   x2 <- runif(n, 0, 1)
   x3 <- runif(n, 0, 1)
   model1 <- 1 - 2*x1
   model2 <- -3 + 8*x2
   model3 <- -4 + 4*x3
   prob1 <- exp(model1)/(1 + exp(model1))
   prob2 <- exp(model2)/(1 + exp(model2))
   prob3 <- exp(model3)/(1 + exp(model3))
   prob_avg <- (prob1 + prob2 + prob3)/3
   y <- rbinom(n,1,prob_avg)
   fit <- glm(y ~ x1 + x2 + x3, family = binomial)
   p[i,1] <- summary(fit)$coefficients[2,4]
   p[i,2] <- summary(fit)$coefficients[3,4]
   p[i,3] <- summary(fit)$coefficients[4,4]
}
mean(p[,1] < .05|p[,2] < .05|p[,3] < .05)
```
