---
title: "Practice B"
author: "Jack Cunningham"
format: html
editor: visual
---

1\)

```{r}
library(epitools)
mydata=array(c(20, 11, 132, 54, 1, 6, 10, 97), dim=c(2, 2, 2), dimnames=list(dfndsrace=c("White", "Black"), dthpnlt=c("Yes", "No"), vctmsrace=c("White", "Black")))
mydata
epitools::oddsratio(x = c(20, 11, 132, 54, 1, 6, 10, 97), method="wald")
20*54/(132*11)
```

```{r}
p_1 = 20/(20+132)
p_2 = 11/(11 + 54)
odds_1 = p_1/(1 - p_1)
odds_2 = p_2/(1 - p_2)
c(odds_1,odds_2)
odds_1/odds_2
odds_2/odds_1
```

2\)

```{r}
p_1 = 1/(1 + 10)
p_2 = 6/(6 + 97)
odds_1 = p_1/(1 - p_1)
odds_2 = p_2/(1 - p_2)
odds_1;odds_2
odds_1/odds_2
epitools::oddsratio(x = c(1,6,10,97), method="wald")
```

3\)

```{r}
epitools::oddsratio(x = c(21,17,142,151), method="wald")
```

6\)

```{r}
DescTools::BreslowDayTest(mydata)
```

10\)

```{r}
mantelhaen.test(mydata,correct=TRUE)
```

13\)

```{r}
mean = 7.1
1 - ppois(10,7.1)
```

14\)

```{r}
1 - ppois(10,6.1)
```

15\)

```{r}
library(binom)
binom::binom.confint(2,20)
```

18\)

```{r}
binom.test(x = 2,n = 20, p = .25,alternative="less")
```
